export const SET_INPUT_FILES: 'SET_INPUT_FILES' = 'SET_INPUT_FILES';
export const GET_INPUT_FILES: 'GET_INPUT_FILES' = 'GET_INPUT_FILES';
export const SET_OUTPUT_FILES: 'SET_OUTPUT_FILES' = 'SET_OUTPUT_FILES';
export const GET_OUTPUT_FILES: 'GET_OUTPUT_FILES' = 'GET_OUTPUT_FILES';
export const SET_AVAILABLE_FORMATS: 'SET_AVAILABLE_FORMATS' = 'SET_AVAILABLE_FORMATS';